# Generated by Django 6.0 on 2025-12-30 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, unique=True)),
                ('device_key_hash', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('title', models.CharField(max_length=120)),
                ('note_internal', models.TextField(blank=True, default='')),
                ('cancel_pin_hash', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancel_fail_count', models.PositiveIntegerField(default=0)),
                ('cancel_locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_by_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.accessdevice')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.room')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.room')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('device', 'Device'), ('admin', 'Admin')], max_length=10)),
                ('actor_label', models.CharField(blank=True, default='', max_length=80)),
                ('action', models.CharField(max_length=40)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.reservation')),
            ],
            options={
                'indexes': [models.Index(fields=['at'], name='reservation_at_9ab6a9_idx'), models.Index(fields=['action'], name='reservation_action_ce08de_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['room', 'start_at'], name='reservation_room_id_a89ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['room', 'end_at'], name='reservation_room_id_1ef63b_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'start_at'], name='reservation_status_e8c444_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['start_at'], name='reservation_start_a_7df526_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['end_at'], name='reservation_end_at_45adf9_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['room', 'start_at'], name='reservation_room_id_a60f3b_idx'),
        ),
    ]
