# Generated by Django 6.0 on 2026-01-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_series_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='color',
            field=models.CharField(default='#e3f2fd', max_length=20),
        ),
    ]
