# Generated by Django 4.2.30 on 2026-06-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='requires_approval',
            field=models.BooleanField(default=False, verbose_name='예약 승인 필요'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
    ]
