# Generated by Django 4.2.30 on 2026-06-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_room_requires_approval_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='신청자 이메일'),
        ),
    ]
