# Generated by Django 4.2.30 on 2026-07-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_reservation_email_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='series_repeat_until',
            field=models.DateField(blank=True, null=True, verbose_name='반복 종료일'),
        ),
    ]
